name: Nonprod deploy

on:
  push:
    branches:
      - "main"
      - "release/**"
      - "task/**"
    paths:
      - .github/workflows/default-deploy.yml

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.apply.outputs.a_prime_url }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Export credentials (GCP)
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > gcp.json

      - name: Export credentials (GCP)
        run: export GOOGLE_APPLICATION_CREDENTIALS=gcp.json

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=tfstate-nonp"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json

      - name: Switch TF Workspace
        id: workspace
        run: terraform workspace select ${GITHUB_REF_NAME/\//-} || terraform workspace new ${GITHUB_REF_NAME/\//-}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json

      - name: TF Plan
        id: plan
        run: >-
          terraform plan -input=false
          -var="google_project_id=${{ vars.GCP_PROJECT_ID }}"
          -var="infra_namespace=${GITHUB_REF_NAME/\//-}"
          -var="commit_hash=${GITHUB_SHA}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json

      - name: TF Apply
        id: apply
        run: >-
          terraform plan -input=false
          -var="google_project_id=${{ vars.GCP_PROJECT_ID }}"
          -var="infra_namespace=${GITHUB_REF_NAME/\//-}"
          -var="commit_hash=${GITHUB_SHA}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json
