name: Branch Deleted

on: delete

jobs:
  delete:
    if: github.ref != "ref/heads/main" && github.ref != "ref/heads/pre-main"
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"