name: Branch Deleted

on: delete

jobs:
  workflow-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: github.event.ref_type
        run: echo "github.event.ref_type = ${{ github.event.ref_type }}"
      - name: github.event.ref
        run: echo "github.event.ref = ${{ github.event.ref }}"
      - name: Comparison logic for job "delete"
        run: echo "(github.event.ref_type == 'branch' && github.event.ref != 'pre-main' && github.event.ref != 'main')"
      - name: secrets.SOME_SECRET
        run: echo "secrets.SOME_SECRET = ${{ secrets.SOME_SECRET }}"
      - name: github.workspace
        run: echo "github.workspace = ${{ github.workspace }}"
  delete:
    runs-on: ubuntu-latest
    if: (github.event.ref_type == 'branch' && github.event.ref != 'pre-main' && github.event.ref != 'main')
    steps:
      - name: Destroying infra
        run: echo "Destroying infra for ${{ github.event.ref_type }} ${{ github.event.ref }}"