name: Branch Deleted

on: delete

jobs:
  delete:
    if: |
      (github.head_ref != 'main' && github.head_ref != 'pre-main')
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"