name: Branch Deleted

on:
  delete:
    branches:
      - '!main'
      - '!pre-main'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"

# jobs:
#   delete:
#     if: (github.event.ref != 'main' && github.event.ref != 'pre-main')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clean up
#         run: |
#           echo "Clean up for branch ${{ github.event.ref }}"