name: Destroy infra on branch deletion

on:
  push:
    branches:
      - "release/**"
      - "task/**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.apply.outputs.a_prime_url }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Group of log lines
        run: |
            echo "Destroy!!! Burn!!!"
