name: Branch Deleted

on: delete

jobs:
  workflow-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: github.event.ref_type
        run: echo "github.event.ref_type = ${{ github.event.ref_type }}"
      - name: github.event.ref
        run: echo "github.event.ref = ${{ github.event.ref }}"
      - name: Comparison logic for job "delete"
        run: echo "(github.event.ref_type == 'branch' && github.event.ref != 'pre-main' && github.event.ref != 'main')"

      - name: vars.SOME_VARIABLE
        run: echo "vars.SOME_VARIABLE = ${{ vars.SOME_VARIABLE }}"
      - name: github.ref
        run: echo "github.ref = ${{ github.ref }}"

      - name: BRANCH_NAME = ${{ github.event.ref }}
        run: BRANCH_NAME = ${{ github.event.ref }}
      - name: BRANCH_NAME/\//-
        run: echo "BRANCH_NAME/\//- = ${BRANCH_NAME/\//-}"
      - name: github.event.ref/\//-
        run: echo "github.event.ref/\//- = ${github.event.ref/\//-}"

  delete:
    runs-on: ubuntu-latest
    if: (github.event.ref_type == 'branch' && github.event.ref != 'pre-main' && github.event.ref != 'main')
    steps:
      - name: Destroying infra
        run: echo "Destroying infra for ${{ github.event.ref_type }} ${{ github.event.ref }}"