name: Manually triggered workflow

on:
  delete:
  push:
    branches:
      - "*"
  workflow_call:
  workflow_dispatch:

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: github.event.action
        run: echo "github.event.action = ${{ github.event.action }}"
      - name: github.event.ref_type
        run: echo "github.event.ref_type = ${{ github.event.ref_type }}"
      - name: github.ref_name
        run: echo "github.ref_name = ${{ github.ref_name }}"
      - name: github.event.ref
        run: echo "github.event.ref = ${{ github.event.ref }}"

      - name: Comparison logic for job "delete"
        run: echo "(github.event.ref_type == 'branch' && github.event.ref != 'pre-main' && github.event.ref != 'main')"

      - name: vars.SOME_VARIABLE
        run: echo "vars.SOME_VARIABLE = ${{ vars.SOME_VARIABLE }}"
      - name: github.ref
        run: echo "github.ref = ${{ github.ref }}"

      - name: BRANCH_NAME/\//-
        env:
          BRANCH_NAME: ${{github.event.ref}}
        run: echo "BRANCH_NAME/\//- = ${BRANCH_NAME/\//-}"
